- action:
  - data:
      brightness: 163
      entity_id: light.dimlight53a
    service: light.turn_on
  alias: '1520496526'
  condition:
    condition: and
    conditions: []
  id: '1520496526'
  trigger: []
- action:
  - data:
      entity_id: cover.dooya1442
      position: 0
    service: cover.set_cover_position
  - data:
      brightness: 255
      entity_id: light.dimlight53a
    service: light.turn_on
  alias: '1520498668'
  condition:
    condition: and
    conditions: []
  id: '1520498668'
  trigger: []
- action:
  - data:
      entity_id: cover.dooya1442
      position: 64
    service: cover.set_cover_position
  alias: '1520499863'
  condition:
    condition: and
    conditions: []
  id: '1520499863'
  trigger: []
- action:
  - data:
      entity_id: light.lightfec51
    service: light.turn_on
  alias: '1521008414'
  condition:
    condition: and
    conditions: []
  id: '1521008414'
  trigger: []
- action:
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  - data:
      entity_id: light.lightfec52
    service: light.turn_on
  alias: '1521078541'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: cover.cover32402
      state: closed
    - condition: state
      entity_id: media_player.yodar97f
      state: playing
    - condition: state
      entity_id: cover.dooya1442
      state: open
    - condition: state
      entity_id: cover.cover32401
      state: open
  id: '1521078541'
  trigger:
  - entity_id: cover.cover32402
    platform: state
    to: closed
  - entity_id: media_player.yodar97f
    platform: state
    to: playing
  - entity_id: cover.dooya1442
    platform: state
    to: open
  - entity_id: cover.cover32401
    platform: state
    to: open
