- action:
  - data:
      entity_id: light.lnlight19bf
    service: homeassistant.turn_off
  - data:
      entity_id: switch.socket2b17
    service: homeassistant.turn_off
  - data:
      entity_id: cover.cover32402
    service: cover.close_cover
  - data:
      entity_id: cover.cover32401
    service: cover.close_cover
  alias: '1519632067'
  condition:
    condition: or
    conditions: []
  id: '1519632067'
  trigger:
  - entity_id: binary_sensor.door115
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: cover.cover32401
    service: cover.open_cover
  - data:
      entity_id: switch.socket2b17
    service: homeassistant.turn_off
  - data:
      entity_id: light.lnlight19bf
    service: homeassistant.turn_off
  - data:
      entity_id: cover.cover32402
    service: cover.open_cover
  alias: '1519697285'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.door694
      state: 'on'
  id: '1519697285'
  trigger:
  - at: 00:00
    platform: time
- action:
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  alias: '1519714634'
  condition:
    condition: or
    conditions:
    - after: '15:02:00'
      before: '15:02:00'
      condition: time
  id: '1519714634'
  trigger:
  - at: '15:02'
    platform: time
- action:
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  alias: '1519715017'
  condition:
    condition: or
    conditions:
    - after: '15:05'
      before: '15:05'
      condition: time
  id: '1519715017'
  trigger:
  - at: '15:05'
    platform: time
- action:
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_play_pause
  alias: '1519716461'
  condition:
    condition: or
    conditions: []
  id: '1519716461'
  trigger: []
- action:
  - data:
      entity_id: light.lightd61
    service: light.turn_on
  - data:
      entity_id: light.lnlight8c13
    service: light.turn_on
  alias: '1519722740'
  condition:
    condition: or
    conditions: []
  id: '1519722740'
  trigger: []
- action:
  - data:
      entity_id: cover.dooya1442
    service: cover.close_cover
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_play_pause
  - data:
      entity_id: light.lightd61
    service: light.turn_off
  alias: '1519801544'
  condition:
    condition: or
    conditions:
    - after: sunset
      condition: sun
    - after: sunrise
      condition: sun
    - condition: state
      entity_id: media_player.yodar97f
      state: turn_off
    - after: '15:06'
      before: '15:06'
      condition: time
  id: '1519801544'
  trigger:
  - event: sunset
    platform: sun
  - event: sunrise
    platform: sun
  - entity_id: media_player.yodar97f
    platform: state
    to: turn_off
  - at: '15:06'
    platform: time
- action:
  - data:
      entity_id: cover.dooya1442
    service: cover.close_cover
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_play_pause
  - data:
      entity_id: light.lightd61
    service: light.turn_off
  alias: '1519801799'
  condition:
    condition: or
    conditions:
    - after: sunset
      condition: sun
    - after: sunrise
      condition: sun
    - condition: state
      entity_id: media_player.yodar97f
      state: turn_off
    - after: '15:06'
      before: '15:06'
      condition: time
  id: '1519801799'
  trigger:
  - event: sunset
    platform: sun
  - event: sunrise
    platform: sun
  - entity_id: media_player.yodar97f
    platform: state
    to: turn_off
  - at: '15:06'
    platform: time
- action:
  - data:
      entity_id: cover.dooya1442
    service: cover.close_cover
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_play_pause
  - data:
      entity_id: light.lightd61
    service: light.turn_off
  alias: '1519801861'
  condition:
    condition: or
    conditions:
    - after: sunset
      condition: sun
    - after: sunrise
      condition: sun
    - condition: state
      entity_id: media_player.yodar97f
      state: turn_off
    - after: '15:06'
      before: '15:06'
      condition: time
  id: '1519801861'
  trigger:
  - event: sunset
    platform: sun
  - event: sunrise
    platform: sun
  - entity_id: media_player.yodar97f
    platform: state
    to: turn_off
  - at: '15:06'
    platform: time
- action:
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  - data:
      entity_id: cover.cover32402
    service: cover.open_cover
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_off
  alias: '1519802984'
  condition:
    condition: or
    conditions:
    - after: '19:21'
      before: '19:21'
      condition: time
    - after: sunrise
      condition: sun
    - condition: state
      entity_id: light.lnlight8c12
      state: 'off'
  id: '1519802984'
  trigger:
  - at: '19:21'
    platform: time
  - event: sunrise
    platform: sun
  - entity_id: light.lnlight8c12
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  alias: '1519810564'
  condition:
    condition: or
    conditions: []
  id: '1519810564'
  trigger:
  - entity_id: binary_sensor.panel44a0
    platform: state
    to: '2'
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  alias: '1519811075'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.panel44a0
      state: '2'
  id: '1519811075'
  trigger:
  - entity_id: binary_sensor.panel44a0
    platform: state
    to: '2'
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  alias: '1519872185'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.panel44a0
      state: '2'
  id: '1519872185'
  trigger:
  - entity_id: binary_sensor.panel44a0
    platform: state
    to: '2'
