- action:
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_on
  alias: '1524201677'
  condition:
    condition: and
    conditions: []
  id: '1524201677'
  trigger:
  - at: '13:30'
    platform: time
- action:
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  alias: '1524201716'
  condition:
    condition: and
    conditions: []
  id: '1524201716'
  trigger:
  - entity_id: light.lnlight1a621
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: cover.dooya1442
      position: '77'
    service: cover.open_cover
  alias: '1526609609'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: cover.dooya1442
      state: 'on'
  id: '1526609609'
  trigger:
  - entity_id: cover.dooya1442
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_on
  - data:
      entity_id: cover.dooya1442
      position: '89'
    service: cover.open_cover
  - data:
      entity_id: light.light4a0
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  - data:
      entity_id: cover.cover32402
    service: cover.open_cover
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  - data:
      entity_id: cover.cover32401
    service: cover.open_cover
  alias: '1526614559'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.socket2b17
      state: 'on'
    - condition: state
      entity_id: light.lnlight19bf
      state: 'on'
    - condition: state
      entity_id: cover.dooya1442
      state: 'on'
    - condition: state
      entity_id: light.light4a0
      state: 'on'
    - condition: state
      entity_id: light.lnlight1a622
      state: 'on'
    - condition: state
      entity_id: cover.cover32402
      state: 'on'
    - condition: state
      entity_id: light.lnlight1a621
      state: 'on'
    - condition: state
      entity_id: cover.cover32401
      state: 'on'
  id: '1526614559'
  trigger:
  - entity_id: switch.socket2b17
    platform: state
    to: 'on'
  - entity_id: light.lnlight19bf
    platform: state
    to: 'on'
  - entity_id: cover.dooya1442
    platform: state
    to: 'on'
  - entity_id: light.light4a0
    platform: state
    to: 'on'
  - entity_id: light.lnlight1a622
    platform: state
    to: 'on'
  - entity_id: cover.cover32402
    platform: state
    to: 'on'
  - entity_id: light.lnlight1a621
    platform: state
    to: 'on'
  - entity_id: cover.cover32401
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  alias: '1526631572'
  condition:
    condition: and
    conditions: []
  id: '1526631572'
  trigger: []
