- action:
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a622
    service: light.turn_on
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  alias: '1521687250'
  condition:
    condition: and
    conditions: []
  id: '1521687250'
  trigger: []
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_off
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_off
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_off
  alias: '1521687327'
  condition:
    condition: and
    conditions: []
  id: '1521687327'
  trigger: []
- action:
  - data:
      entity_id: sensor.sensor50001fcef3975
    service: sensor.turn_off
  alias: '1523498148'
  condition:
    condition: and
    conditions: []
  id: '1523498148'
  trigger:
  - entity_id: sensor.sensor50001fcef3973
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: sensor.sensor50001fcef3975
    service: sensor.turn_off
  alias: '1523498153'
  condition:
    condition: and
    conditions: []
  id: '1523498153'
  trigger:
  - entity_id: sensor.sensor50001fcef3973
    platform: state
    to: 'on'
