- action:
  - data:
      entity_id: light.lightd12
    service: light.turn_on
  alias: '1519886255'
  id: '1519886255'
  trigger:
  - entity_id: cover.cover32401
    platform: state
    to: open
- action:
  - data:
      entity_id: light.lightd12
    service: light.turn_on
  alias: '1519886861'
  condition:
    condition: and
    conditions: []
  id: '1519886861'
  trigger:
  - event_type: binary_sensor.panel44a0_1_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_on
  alias: '1519887467'
  condition:
    condition: and
    conditions: []
  id: '1519887467'
  trigger:
  - event_type: binary_sensor.panel44a0_1_pressed
    platform: event
