- action:
  - data:
      brightness: 163
      entity_id: light.dimlight53a
    service: light.turn_on
  alias: '1520496526'
  condition:
    condition: and
    conditions: []
  id: '1520496526'
  trigger: []
- action:
  - data:
      entity_id: cover.dooya1442
      position: 0
    service: cover.set_cover_position
  - data:
      brightness: 255
      entity_id: light.dimlight53a
    service: light.turn_on
  alias: '1520498668'
  condition:
    condition: and
    conditions: []
  id: '1520498668'
  trigger: []
- action:
  - data:
      entity_id: cover.dooya1442
      position: 64
    service: cover.set_cover_position
  alias: '1520499863'
  condition:
    condition: and
    conditions: []
  id: '1520499863'
  trigger: []
