- action:
  - data:
      entity_id: light.lightd12
    service: light.turn_on
  alias: '1519886255'
  id: '1519886255'
  trigger:
  - entity_id: cover.cover32401
    platform: state
    to: open
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_on
  alias: '1519887467'
  condition:
    condition: and
    conditions: []
  id: '1519887467'
  trigger:
  - event_type: binary_sensor.panel44a0_1_pressed
    platform: event
- action:
  - data:
      entity_id: light.lnlight1a621
    service: light.turn_on
  - data:
      entity_id: light.dimlight53a
    service: light.turn_off
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_previous_track
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_off
  - data:
      entity_id: light.lightfec53
    service: light.turn_on
  alias: '1519890785'
  condition:
    condition: and
    conditions: []
  id: '1519890785'
  trigger:
  - event_type: binary_sensor.panel44a0_2_pressed
    platform: event
- action:
  - data:
      entity_id: light.lightfec53
    service: light.turn_on
  - data:
      entity_id: light.lightd12
    service: light.turn_on
  alias: '1519891265'
  condition:
    condition: or
    conditions:
    - after: '16:59'
      before: '16:59'
      condition: time
    - after: sunrise
      condition: sun
    - after: sunset
      condition: sun
    - condition: state
      entity_id: media_player.yodar97f
      state: turn_off
  id: '1519891265'
  trigger:
  - at: '16:59'
    platform: time
  - event: sunrise
    platform: sun
  - event: sunset
    platform: sun
  - entity_id: media_player.yodar97f
    platform: state
    to: turn_off
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_off
  alias: '1519892714'
  condition:
    condition: and
    conditions: []
  id: '1519892714'
  trigger: []
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.playing
  alias: '1519893067'
  condition:
    condition: and
    conditions: []
  id: '1519893067'
  trigger: []
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_next_track
  alias: '1519896646'
  condition:
    condition: and
    conditions: []
  id: '1519896646'
  trigger:
  - event_type: binary_sensor.door115_off_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.off
  alias: '1519897016'
  condition:
    condition: or
    conditions:
    - after: '19:36'
      before: '19:36'
      condition: time
    - condition: state
      entity_id: switch.socket2b17
      state: 'on'
  id: '1519897016'
  trigger:
  - at: '19:36'
    platform: time
  - entity_id: switch.socket2b17
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_previous_track
  alias: '1519897051'
  condition:
    condition: and
    conditions: []
  id: '1519897051'
  trigger:
  - event_type: binary_sensor.door115_on_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_previous_track
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  alias: '1519897210'
  condition:
    condition: and
    conditions: []
  id: '1519897210'
  trigger:
  - event_type: binary_sensor.door115_on_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.on
  alias: '1519897348'
  condition:
    condition: and
    conditions: []
  id: '1519897348'
  trigger:
  - event_type: binary_sensor.door115_on_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_on
  alias: '1519897531'
  condition:
    condition: and
    conditions: []
  id: '1519897531'
  trigger:
  - event_type: binary_sensor.door115_on_pressed
    platform: event
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_previous_track
  alias: '1519897891'
  condition:
    condition: and
    conditions: []
  id: '1519897891'
  trigger:
  - entity_id: binary_sensor.door115
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: light.lightd12
    service: light.turn_off
  alias: '1519898109'
  condition:
    condition: and
    conditions: []
  id: '1519898109'
  trigger: []
- action:
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  - data:
      entity_id: light.lnlight8c13
    service: light.turn_on
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_on
  alias: '1520213890'
  condition:
    condition: and
    conditions: []
  id: '1520213890'
  trigger:
  - entity_id: common
    platform: state
    to: time
- action:
  - data:
      entity_id: cover.dooya1442
    service: cover.open_cover
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  - data:
      entity_id: light.lnlight8c11
    service: light.turn_on
  alias: '1520213991'
  condition:
    condition: and
    conditions: []
  id: '1520213991'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_on
  - data:
      entity_id: light.lnlight8c12
    service: light.turn_on
  alias: '1520214024'
  condition:
    condition: and
    conditions: []
  id: '1520214024'
  trigger:
  - entity_id: binary_sensor.door115
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: media_player.yodar97f
    service: media_player.turn_off
  - data:
      entity_id: switch.socket2b17
    service: switch.turn_on
  - data:
      entity_id: light.lnlight8c13
    service: light.turn_on
  alias: '1520214170'
  condition:
    condition: and
    conditions: []
  id: '1520214170'
  trigger:
  - event_type: binary_sensor.panel44a0_1_pressed
    platform: event
- action:
  - data:
      entity_id: light.lnlight8c13
    service: light.turn_on
  - data:
      entity_id: media_player.yodar97f
    service: media_player.media_play_pause
  alias: '1520214416'
  condition:
    condition: and
    conditions: []
  id: '1520214416'
  trigger:
  - entity_id: switch.socket2b17
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: light.lnlight8c13
    service: light.turn_on
  - data:
      entity_id: light.lightd12
    service: light.turn_off
  - data:
      entity_id: light.lnlight19bf
    service: light.turn_on
  alias: '1520214469'
  condition:
    condition: or
    conditions:
    - after: '10:47'
      before: '10:47'
      condition: time
    - condition: state
      entity_id: media_player.yodar97f
      state: 'off'
  id: '1520214469'
  trigger:
  - entity_id: media_player.yodar97f
    platform: state
    to: 'off'
